name: Azure Container Web App Deployment
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: list files
        run: ls -la

      - name: Check Docker version
        run: docker --version

      - name: Docker image build
        run: |
          docker build -t python_custom_app:latest .
          docker images

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure Login
        run: |
          az account show
          az account list -o table

      - name: Create Resource Group
        run: |
          az group create \
            --name python-app-rg \
            --location eastus

      - name: Create Azure container registry
        run: |
          az acr create \
            --resource-group python-app-rg \
            --name pythonappregistrytestingpurpose \
            --sku Basic

      - name: Login to ACR
        run: |
          az acr login --name pythonappregistrytestingpurpose

      - name: Tag Docker Image and push to ACR
        run: |
          docker tag python_custom_app:latest pythonappregistrytestingpurpose.azurecr.io/python_custom_app:${{ github.sha }}
          docker push pythonappregistrytestingpurpose.azurecr.io/python_custom_app:${{ github.sha }}
      - name: Create Azure Web App for Containers
        run: |
          az webapp create \
            --resource-group python-app-rg \
            --plan python-app-service-plan \
            --name python-container-webapp \
            --deployment-container-image-name pythonappregistrytestingpurpose.azurecr.io/python_custom_app:${{ github.sha }}
      - name: Configure Web App to use ACR
        run: |
          az webapp config container set \
            --resource-group python-app-rg \
            --name python-container-webapp \
            --docker-custom-image-name pythonappregistrytestingpurpose.azurecr.io/python_custom_app:${{ github.sha }}
      - name: Restart Web App
        run: |
          az webapp restart \
            --resource-group python-app-rg \
            --name python-container-webapp
      - name: Verify Web App Deployment
        run: |
          az webapp show \
            --resource-group python-app-rg \
            --name python-container-webapp \
            --query "state"
      - name: Get Web App URL
        run: |
          az webapp show \
            --resource-group python-app-rg \
            --name python-container-webapp \
            --query "defaultHostName" -o tsv
